# -*- coding: utf-8 -*-
"""Airbnb_ML_Track1_Final_TeamB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBBRHQoUm_Z5Bi7PIDJutW3fpHdyAHSn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

RANDOM_STATE = 42

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

!ls -lah

import pandas as pd

df = pd.read_csv("/content/AB_NYC_2019.csv")
df.head()

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isna().sum().sort_values(ascending=False).head(10))

df = df.drop(columns=["id", "name", "host_id", "host_name", "last_review"])
df.head()

df["reviews_per_month"] = df["reviews_per_month"].fillna(0)

print(df.isna().sum().sort_values(ascending=False))

X = df.drop("price", axis=1)
y = df["price"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=RANDOM_STATE
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numerical_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical:", categorical_cols)
print("Numerical:", numerical_cols)

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Preprocessing for numerical data
numeric_transformer = StandardScaler()

# Preprocessing for categorical data
categorical_transformer = OneHotEncoder(handle_unknown="ignore")

# Combine preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_cols),
        ("cat", categorical_transformer, categorical_cols)
    ]
)

from sklearn.linear_model import LinearRegression

linear_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

# Train
linear_model.fit(X_train, y_train)

# Predict
y_pred_linear = linear_model.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

r2 = r2_score(y_test, y_pred_linear)
mae = mean_absolute_error(y_test, y_pred_linear)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_linear))

print("Linear Regression Performance:")
print("R²:", round(r2, 4))
print("MAE:", round(mae, 2))
print("RMSE:", round(rmse, 2))

from sklearn.linear_model import Ridge

ridge_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", Ridge(alpha=1.0))
])

ridge_model.fit(X_train, y_train)

y_pred_ridge = ridge_model.predict(X_test)

r2_ridge = r2_score(y_test, y_pred_ridge)
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
rmse_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))

print("Ridge Regression Performance:")
print("R²:", round(r2_ridge, 4))
print("MAE:", round(mae_ridge, 2))
print("RMSE:", round(rmse_ridge, 2))

# Get feature names after preprocessing
feature_names = (
    numerical_cols +
    list(ridge_model.named_steps["preprocessor"]
         .named_transformers_["cat"]
         .get_feature_names_out(categorical_cols))
)

coefficients = ridge_model.named_steps["model"].coef_

import pandas as pd

coef_df = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
})

coef_df = coef_df.sort_values(by="Coefficient", key=abs, ascending=False)

coef_df.head(15)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df["price"], bins=100)
plt.title("Price Distribution")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.xlim(0, 600)
plt.show()

import numpy as np

y_log = np.log1p(y)

X_train, X_test, y_train_log, y_test_log = train_test_split(
    X, y_log,
    test_size=0.2,
    random_state=RANDOM_STATE
)

linear_model_log = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

linear_model_log.fit(X_train, y_train_log)

y_pred_log = linear_model_log.predict(X_test)

r2_log = r2_score(y_test_log, y_pred_log)
mae_log = mean_absolute_error(y_test_log, y_pred_log)
rmse_log = np.sqrt(mean_squared_error(y_test_log, y_pred_log))

print("Log-Linear Regression Performance:")
print("R²:", round(r2_log, 4))
print("MAE:", round(mae_log, 4))
print("RMSE:", round(rmse_log, 4))

from sklearn.linear_model import Ridge

ridge_model_log = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", Ridge(alpha=1.0))
])

ridge_model_log.fit(X_train, y_train_log)

y_pred_ridge_log = ridge_model_log.predict(X_test)

r2_ridge_log = r2_score(y_test_log, y_pred_ridge_log)
mae_ridge_log = mean_absolute_error(y_test_log, y_pred_ridge_log)
rmse_ridge_log = np.sqrt(mean_squared_error(y_test_log, y_pred_ridge_log))

print("Log-Ridge Regression Performance:")
print("R²:", round(r2_ridge_log, 4))
print("MAE:", round(mae_ridge_log, 4))
print("RMSE:", round(rmse_ridge_log, 4))

from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=80,       # slightly fewer trees
        max_depth=15,          # limit depth
        min_samples_split=10,
        random_state=RANDOM_STATE,
        n_jobs=-1
    ))
])

rf_model.fit(X_train, y_train_log)

y_pred_rf = rf_model.predict(X_test)

r2_rf = r2_score(y_test_log, y_pred_rf)
mae_rf = mean_absolute_error(y_test_log, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test_log, y_pred_rf))

print("Random Forest (Log Target) Performance:")
print("R²:", round(r2_rf, 4))
print("MAE:", round(mae_rf, 4))
print("RMSE:", round(rmse_rf, 4))

import pandas as pd

rf = rf_model.named_steps["model"]

feature_names = rf_model.named_steps["preprocessor"].get_feature_names_out()

importances = rf.feature_importances_

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

importance_df.head(15)

import pandas as pd

results_df = pd.DataFrame({
    "Model": [
        "Linear (Raw)",
        "Linear (Log)",
        "Ridge (Log)",
        "Random Forest (Log)"
    ],
    "R2": [
        0.1359,
        r2_log,
        r2_ridge_log,
        r2_rf
    ],
    "MAE": [
        68.15,
        mae_log,
        mae_ridge_log,
        mae_rf
    ],
    "RMSE": [
        195.52,
        rmse_log,
        rmse_ridge_log,
        rmse_rf
    ]
})

results_df

import matplotlib.pyplot as plt
import numpy as np

residuals = y_test_log - y_pred_rf

plt.figure(figsize=(8,6))
plt.scatter(y_pred_rf, residuals, alpha=0.3)
plt.axhline(0, color='red', linestyle='--')
plt.xlabel("Predicted Log Price")
plt.ylabel("Residuals")
plt.title("Residual Plot - Random Forest (Log Target)")
plt.show()

from sklearn.preprocessing import StandardScaler

# Select features for clustering
cluster_features = df[[
    "price",
    "availability_365",
    "number_of_reviews",
    "reviews_per_month",
    "minimum_nights",
    "calculated_host_listings_count",
    "latitude",
    "longitude"
]].copy()

# Log-transform price (consistent with regression insight)
cluster_features["price"] = np.log1p(cluster_features["price"])

# Scale features
scaler = StandardScaler()
cluster_scaled = scaler.fit_transform(cluster_features)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []

K_range = range(2, 8)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10)
    kmeans.fit(cluster_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(K_range, inertia, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal K")
plt.show()

kmeans_final = KMeans(n_clusters=4, random_state=RANDOM_STATE, n_init=10)
df["Cluster"] = kmeans_final.fit_predict(cluster_scaled)

df["Cluster"].value_counts()

cluster_summary = df.groupby("Cluster")[[
    "price",
    "availability_365",
    "number_of_reviews",
    "reviews_per_month",
    "minimum_nights",
    "calculated_host_listings_count"
]].mean()

cluster_summary

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.hist(df["price"], bins=50)
plt.title("Raw Price Distribution")

plt.subplot(1,2,2)
plt.hist(np.log1p(df["price"]), bins=50)
plt.title("Log-Transformed Price Distribution")

plt.tight_layout()
plt.show()

import seaborn as sns

plt.figure(figsize=(10,8))
corr = df[[
    "price",
    "minimum_nights",
    "number_of_reviews",
    "reviews_per_month",
    "availability_365",
    "calculated_host_listings_count"
]].corr()

sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()